# Railway configuration for Backend service
# Dockerfile at root will be auto-detected

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run server:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
