# Railway configuration for multi-service setup
# railway.json takes precedence for multi-service configuration
# This file is kept for reference only

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npm run server:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
