# Test Docker Compose configuration
# Run tests with: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

services:
  test:
    image: node:20-alpine
    working_dir: /app
    environment:
      - NODE_ENV=test
      - VITE_DATABASE_URL=postgres://testuser:testpass@postgres-test:5432/testdb
    networks:
      - nexus-test
    depends_on:
      postgres-test:
        condition: service_healthy

  backend-test:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run server:test"
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - PORT=5000
      - CI=true
      - VITE_DATABASE_URL=postgres://testuser:testpass@postgres-test:5432/testdb
      - JWT_SECRET=test-secret
    networks:
      - nexus-test
    depends_on:
      postgres-test:
        condition: service_healthy

  postgres-test:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    networks:
      - nexus-test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

networks:
  nexus-test:
    driver: bridge
